// Bundles frontend/pg-libs.js into a single classic script that the OctoPrint asset pipeline can serve.
// Run via `task build-frontend`.

import {build} from "esbuild";

const banner = `/* PrettyGCode bundled libs - generated by 'task build-frontend', do not edit */`;

await build({
    entryPoints: ["frontend/pg-libs.js"],
    outfile: "octoprint_prettygcode/static/js/lib/pg-libs.bundle.js",
    bundle: true,
    minifyWhitespace: true,
    banner: {js: banner},
});
