// Bundles the frontend into a single classic script that the OctoPrint asset pipeline can serve.
// Run via `task build-frontend`.

import { build } from 'esbuild'

const banner = '/* PrettyGCode bundle - generated by \'task build-frontend\', do not edit */'

await build({
  entryPoints: ['frontend/pg-main.js'],
  outfile: 'octoprint_prettygcode/static/js/pg-main.bundle.js',
  bundle: true,
  banner: { js: banner },
  minifyWhitespace: true,
  minifyIdentifiers: true,
  // Must stay false: minifySyntax turns "\n" literals into raw newline bytes that OctoPrint's
  // plugin-bundle wrapper indents and corrupts, breaking our bundle.
  // If set to true, the nozzle and objects no longer appear on the bed plate.
  minifySyntax: false
})
